{{- if .Values.frontend.healthCheckPolicy.enabled }}
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: {{ include "chart.fullname" . }}-frontend-hck
  namespace: {{ .Release.Namespace }}
spec:
  default:
    checkIntervalSec: 5
    timeoutSec: 5
    healthyThreshold: 2
    unhealthyThreshold: 2
    logConfig:
      enabled: false
    config:
      type: HTTP
      httpHealthCheck:
        port: {{ .Values.frontend.targetPort }}
        requestPath: /
        proxyHeader: NONE
  targetRef:
    group: ""
    kind: Service
    name: {{ .Values.frontend.svcName }}
    namespace: {{ .Release.Namespace }}
{{- end }}
