{{- if .Values.gateway.enabled }}
kind: Gateway
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: {{ .Values.gateway.name }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.gateway.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  annotations:
    networking.gke.io/certmap: {{ .Values.gateway.gcpCertMapName }}
spec:
  gatewayClassName: gke-l7-global-external-managed
  listeners:
  - name: https
    protocol: HTTPS
    port: 443
    allowedRoutes:
      namespaces:
        from: {{ .Values.gateway.allowedRoutes.from }}
        selector:
          {{- with .Values.gateway.allowedRoutes.selectorLabels }}
          matchLabels:
            {{- toYaml . | nindent 12 }}
          {{- end }}
  addresses:
  - type: NamedAddress
    value: {{ .Values.gateway.ipName }}
{{- end }}
